n_list= list()
n_list.append(20)
n_list.append(35)
n_list.append(45)
n_list.append(70)
print(n_list)
n_list.insert(1, 100)
print(n_list)

n_list.sort()
print(n_list)
n_list.reverse()
print(n_list)
print(len(n_list))
del(n_list[1])
print(n_list)
n_list.remove(100)
print(n_list)
print(n_list.index(20))
n_list.append(75)
n_list.append(85)
print(n_list)
print("평균 %f " %(sum(n_list)/len(n_list)))
print("범위 %d " %(max(n_list)-min(n_list)))
